services:
  execution-node:
    image: ethereum/client-go:stable
    volumes:
      - Data:/data:rw
      - Secret:/root:ro
    command: 
      --goerli
      --datadir="/data/Goerli"
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.vhosts "*"
      --http.corsdomain "*"
      --http.api eth,net,engine,admin
      --authrpc.jwtsecret /root/jwt.hex
      --authrpc.addr=0.0.0.0
      --authrpc.vhosts "*"
    ports:
      - 8545:8545
      - 30303:30303
      - 8551:8551
  
  beacon-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    volumes:
      - Data:/data:rw
      - Secret:/root:ro
      - Certs:/usr/local/share/ca-certificates:ro
    command:
      --accept-terms-of-use=true
      --datadir="/data/Goerli"
      --jwt-secret="/root/jwt.hex"
      --monitoring-host=0.0.0.0
      --execution-endpoint=http://execution-node:8551
      --genesis-state="/data/genesis.ssz"
      --goerli
      --suggested-fee-recipient=0xd8aE79B8d6Fd0996ed58BA1d3fF6071aA96f1269
      --checkpoint-sync-url=https://goerli.checkpoint-sync.ethpandaops.io
      --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethpandaops.io
    ports:
      - 4000:4000
      - 13000:13000
      - 12000:12000/udp
    depends_on:
      execution-node:
        condition: service_started
  
volumes:
  Data:
  Secret:
  Certs:
